FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# caching nugets
COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Linux -o out

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app/out ./

ENV BOT_TOKEN=YOUR_BOT_TOKEN
ENV BOT_TOKEN=YOUR_TELEGRAM_ID

ENTRYPOINT ["dotnet", "OrgBot.dll"]